### ISSUE TITLE
Run error in CentOS 7/python 2.7.5 

### ISSUE THREAD

**Issue by Guan-Pujun** [CobraLab/MAGeTbrain#45]
Hi, there
I tried to use MAGeTbrain to label subareas in hippocampus,  but I failed.  I'm grateful for the help. What should I do now?

Here is the environment I use: 
CentOS 7;（also tried in Ubuntu 16.04）
python 2.7.5 
numpy 1.7.1
scipy 0.12.1
minc-toolkit-1.0.08-20160205-CentOS_6.7-x86_64
pyminc 0.48
minc-stuffs https://github.com/Mouse-Imaging-Centre/minc-stuffs.git

```
$ mb import /home/fsluser/Desktop/test/brain1_t1.mnc  /home/fsluser/Desktop/test/brain1_labels.mnc
$ mb import /home/fsluser/Desktop/test/brain2_t1.mnc  /home/fsluser/Desktop/test/brain2_labels.mnc
$ mb check
```

WARNING: 2 atlases found. Use an odd number for best results
`$ mb run`
WARNING: 2 atlases found. 
Use an odd number for best results
2 atlases, 1 templates, 2 subjects found
running 2 commands after stage NONE*
Traceback (most recent call last):
File "/home/fsluser/Desktop/MAGeTbrain/bin/qbatch", line 147, in <module>
    o, e = execute("qsub %s" % scriptfile, dry_run = options.dry_run)
File "/home/fsluser/Desktop/MAGeTbrain/bin/qbatch", line 24, in execute
    stdin = subprocess.PIPE, stdout = subprocess.PIPE , stderr = subprocess.PIPE)
File "/usr/lib64/python2.7/subprocess.py", line 711, in **init**
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
File "/home/fsluser/Desktop/MAGeTbrain/bin/mb", line 684, in <module>
    main()
File "/home/fsluser/Desktop/MAGeTbrain/bin/mb", line 191, in main
    options.func(options)
File "/home/fsluser/Desktop/MAGeTbrain/bin/mb", line 291, in command_run
    p.run()
File "/home/fsluser/Desktop/MAGeTbrain/bin/mb", line 526, in run
    self.queue.run(stages=self._get_stage_order())
File "/home/fsluser/Desktop/MAGeTbrain/bin/mb", line 477, in run
    walltime=walltime, processors = processors)  
File "/home/fsluser/Desktop/MAGeTbrain/bin/mb", line 487, in qbatch
    input='\n'.join(commands))
File "/home/fsluser/Desktop/MAGeTbrain/bin/mb", line 438, in execute
    raise Exception("Returns %i :: %s" %( proc.returncode, command ))
Exception: Returns 1 :: qbatch -N mb_templatelib_2016-10-30T12-30-41 --afterok_pattern NONE\* - 4 6:00:00

**Comment by gdevenyi** [comment]
Hi, this version requires cluster integration and substantial customization to work.

Please look at https://github.com/CobraLab/antsRegistration-MAGeT and follow the installation instructions.

**Comment by Guan-Pujun** [comment]
Thank you very much. I'll have a try.
