### ISSUE TITLE
runnig MAGeTbrain on my personal pc

### ISSUE THREAD

**Issue by yuniorcf-80** [CobraLab/MAGeTbrain#48]
Hello,
I am trying to run MAGeTbrain in my personal PC (4xcores, 8GB RAM, Ubuntu 18.04). I know that MAGeTbrain is though to be run in a cluster but it could also be tested in a single computer as well. However, when executing the command "mb run -q parallel" I get an error related to a parallel directory (See below). Could you please tell me what should be wrong?
Thanks

**a view of the Terminal:**
(base) yunior@pc-yunior:~/segm_test2$ mb run -q parallel
5 atlases, 7 templates, 11 subjects found
Traceback (most recent call last):
  File "/home/yunior/MAGeTbrain/bin/mb", line 792, in <module>
    main()
  File "/home/yunior/MAGeTbrain/bin/mb", line 220, in main
    options.func(options)
  File "/home/yunior/MAGeTbrain/bin/mb", line 329, in command_run
    p.run()
  File "/home/yunior/MAGeTbrain/bin/mb", line 608, in run
    self.queue.run(stages=self._get_stage_order())
  File "/home/yunior/MAGeTbrain/bin/mb", line 508, in run
    self.parallel(self.commands[stage])
  File "/home/yunior/MAGeTbrain/bin/mb", line 514, in parallel
    self.execute(command, input='\n'.join(commands))
  File "/home/yunior/MAGeTbrain/bin/mb", line 489, in execute
    stdin=subprocess.PIPE, stdout=2, stderr=2)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'parallel': 'parallel'

**Comment by gdevenyi** [comment]
Hi,

You need to install gnu-parallel: https://packages.ubuntu.com/bionic/parallel

Having said that, 8GB is way too little RAM. You will need to reduce all the parallelization to the minimum, see ``mb run --help``. Our workstations here are 32GB and I wouldn't dream of running MAGeT on them. If you email contact@cobralab.ca we can look into getting you collaborator access to our compute canada allocation to use our tools.
