### ISSUE TITLE
UnicodeDecodeError when running morpho-labelmask branch on niagara

### ISSUE THREAD

**Issue by cbedetti** [CobraLab/MAGeTbrain#49]
Setup : 
-`module load intel/2018.2 openblas/0.2.20 gsl/2.4 minc-toolkit/1.9.16 python/3.6.4-anaconda5.1.0 minc-stuffs/0.1.21^minc-toolkit-1.9.16 mouse-thickness/0.1.1^minc-toolkit-1.9.16 gnu-parallel qbatch ANTs/20180814`
-`morpho-labelmask` at b419005 

Error : 
```$ mb --save run --surfaces --voronoi
1 models, 5 atlases, 21 templates, 145 subjects found
running 167 commands after stage NONE*
exec: qbatch --jobname mb_modelprep_2019-07-02T14-21-02 --depend NONE* --chunksize 400 --walltime 0:15:00 -
...
...
crop_model ...

Traceback (most recent call last):
  File "/scinet/niagara/software/2018a/opt/base/qbatch/2.1.4/bin/qbatch", line 9, in <module>
    load_entry_point('qbatch==2.1.4', 'console_scripts', 'qbatch')()
  File "/scinet/niagara/software/2018a/opt/base/qbatch/2.1.4/lib/python2.7/site-packages/qbatch/qbatch.py", line 706, in qbatchParser
    qbatchDriver(**vars(args))
  File "/scinet/niagara/software/2018a/opt/base/qbatch/2.1.4/lib/python2.7/site-packages/qbatch/qbatch.py", line 395, in qbatchDriver
    in IGNORE_ENV_VARS)])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 10: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/s/sbramba/cbedetti/local/MAGeTbrain/bin/mb", line 1569, in <module>
    main()
  File "/home/s/sbramba/cbedetti/local/MAGeTbrain/bin/mb", line 346, in main
    options.func(options)
  File "/home/s/sbramba/cbedetti/local/MAGeTbrain/bin/mb", line 506, in command_run
    p.run()
  File "/home/s/sbramba/cbedetti/local/MAGeTbrain/bin/mb", line 820, in run
    self.queue.run(stages=self._get_stage_order())
  File "/home/s/sbramba/cbedetti/local/MAGeTbrain/bin/mb", line 769, in run
    stage=stage)
  File "/home/s/sbramba/cbedetti/local/MAGeTbrain/bin/mb", line 796, in qbatch
    input='\n'.join(commands))
  File "/home/s/sbramba/cbedetti/local/MAGeTbrain/bin/mb", line 708, in execute
    raise Exception("Returns %i :: %s" % (proc.returncode, command))
```

Solution : 
Revert to `module load qbatch/git`

**Comment by gdevenyi** [comment]
This isn't a magetbrain bug. Please open at qbatch.

**Comment by gdevenyi** [comment]
Fixed at https://github.com/pipitone/qbatch/pull/193
